apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garage
  template:
    metadata:
      labels:
        app: garage
    spec:
      containers:
      - name: garage
        image: willdeberry/myq-garage
        imagePullPolicy: Always
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: garage-nfs
          mountPath: /usr/bin/garage/schedule.json
          subPath: schedule.json
          readOnly: true
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File
      - name: garage-nfs
        nfs:
          server: 192.168.1.13
          path: /storage/tank/kubernetes/garage
