---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-configmap
  namespace: default
data:
  TZ: "America/New_York"
  DNS1: 192.168.1.1
  adlist: |
    https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    https://mirror1.malwaredomains.com/files/justdomains
    http://sysctl.org/cameleon/hosts
    https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
    https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
    https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
    https://hosts-file.net/ad_servers.txt
    https://raw.githubusercontent.com/CHEF-KOCH/Audio-fingerprint-pages/master/AudioFp.txt
    https://raw.githubusercontent.com/CHEF-KOCH/BarbBlock-filter-list/master/HOSTS.txt
    https://raw.githubusercontent.com/CHEF-KOCH/Canvas-fingerprinting-pages/master/Canvas.txt
    https://raw.githubusercontent.com/CHEF-KOCH/Canvas-Font-Fingerprinting-pages/master/Canvas.txt
    https://raw.githubusercontent.com/CHEF-KOCH/WebRTC-tracking/master/WebRTC.txt
    https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Ads-tracker.txt
    https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/coinminer.txt
    https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Malware.txt
    https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/nsablocklist.txt
    https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/uMatrix/CK's-uMatrix-FilterList.txt
    http://phishing.mailscanner.info/phishing.bad.sites.conf
    https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt
    https://ransomwaretracker.abuse.ch/downloads/CW_C2_DOMBL.txt
    https://ransomwaretracker.abuse.ch/downloads/LY_C2_DOMBL.txt
    https://ransomwaretracker.abuse.ch/downloads/TC_C2_DOMBL.txt
    https://ransomwaretracker.abuse.ch/downloads/TL_C2_DOMBL.txt
    https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
    https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
    https://zerodot1.gitlab.io/CoinBlockerLists/list.txt
    https://zerodot1.gitlab.io/CoinBlockerLists/list_browser.txt
    https://zerodot1.gitlab.io/CoinBlockerLists/list_optional.txt
    https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
    https://raw.githubusercontent.com/w13d/adblockListABP-PiHole/master/Spotify.txt
    https://smokingwheels.github.io/Pi-hole/allhosts
  reglist: |
    ^(.+[-.])??adse?rv(er?|ice)?s?[0-9][-.]
    ^analytics?[-.]
    ^banners?[-.]
    ^count(ers?)?[0-9][-.] ^pixels?[-.]
    ^beacons?[0-9][-.]
    ^stat(s|istics)?[0-9][-.]
    ^telemetry[-.]
    ^track(ers?|ing)?[0-9]*[-.]
    ^traff(ic)?[-.]
    ^adim(age|g)s?[0-9][-.]
    ^adtrack(er|ing)?[0-9][-.]
    ^advert(s|is(ing|ements?))?[0-9][-_.]
    ^aff(iliat(es?|ion))?[-.]
    ^(.+[-.])??m?ad[sxv]?[0-9][-.]
    (^r[[:digit:]]+(.|-+)[[:alnum:]]+-+[[:alnum:]]+-+[[:alnum:]]+.)(googlevideo|gvt1).com$
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - CHOWN
        envFrom:
        - configMapRef:
            name: pihole-configmap
        - secretRef:
            name: pihole
        env:
        - name: DNSMASQ_USER
          value: root
        - name: PIHOLE_UID
          value: "1000"
        - name: PIHOLE_GID
          value: "1000"
        ports:
        - containerPort: 80
          name: pihole-http
          protocol: TCP
        - containerPort: 53
          name: pihole-dns-tcp
          protocol: TCP
        - containerPort: 53
          name: pihole-dns-udp
          protocol: UDP
        volumeMounts:
        - name: pihole-nfs
          mountPath: "/etc/pihole"
          subPath: etc-pihole
          readOnly: false
        - name: pihole-nfs
          mountPath: "/etc/dnsmasq.d"
          subPath: etc-dnsmasq.d
          readOnly: false
      volumes:
      - name: pihole-nfs
        nfs:
          server: 192.168.1.13
          path: /storage/tank/kubernetes/pihole
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-ui-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: pihole
  ports:
  - port: 8000
    targetPort: 80
    name: pihole-admin
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: pihole
  ports:
  - port: 53
    targetPort: 53
    protocol: TCP
    name: 53-tcp
  - port: 53
    targetPort: 53
    protocol: UDP
    name: 53-udp
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-udp
  namespace: default
spec:
  selector:
    app: pihole
  ports:
    - name: 53-udp
      port: 53
      targetPort: 53
      protocol: UDP
  externalTrafficPolicy: Local
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.168.1.50
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-tcp
  namespace: default
spec:
  selector:
    app: pihole
  ports:
    - name: 53-tcp
      port: 53
      targetPort: 53
      protocol: TCP
  externalTrafficPolicy: Local
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.168.1.50
