---
apiVersion: v1
kind: Service
metadata:
  name: transmission-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: transmission
  ports:
  - name: transmission
    port: 9091
    protocol: TCP
    targetPort: transmission
  - name: torrent-tcp
    port: 51412
    protocol: TCP
    targetPort: torrent-tcp
  - name: torrent-udp
    port: 51412
    protocol: UDP
    targetPort: torrent-udp
  externalIPs:
    - "192.168.1.50"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
      - name: transmission
        image: lscr.io/linuxserver/transmission
        imagePullPolicy: Always
        env:
        - name: PUID
          value: '65534'
        - name: PGID
          value: '65534'
        - name: USER
          valueFrom:
            secretKeyRef:
              name: transmission
              key: USER
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: transmission
              key: PASS
        - name: WHITELIST
          value: ''
        ports:
        - containerPort: 9091
          name: transmission
          protocol: TCP
        - containerPort: 51412
          name: torrent-tcp
          protocol: TCP
        - containerPort: 51412
          name: torrent-udp
          protocol: UDP
        volumeMounts:
        - name: transmission-nfs
          mountPath: /downloads
          subPath: torrents/downloads
          readOnly: false
        - name: transmission-nfs
          mountPath: /config
          subPath: torrents/config
          readOnly: false
        - name: transmission-nfs
          mountPath: /videos
          subPath: videos
          readOnly: false
      volumes:
      - name: transmission-nfs
        nfs:
          server: 192.168.1.13
          path: /storage/tank
