---
apiVersion: v1
kind: Service
metadata:
  name: unifi-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: unifi
  ports:
  - name: unifi-http
    port: 8080
    protocol: TCP
    targetPort: unifi-http
  - name: unifi-https
    port: 8443
    protocol: TCP
    targetPort: unifi-https
  - name: unifi-udp1
    port: 3478
    protocol: UDP
    targetPort: unifi-udp1
  - name: unifi-udp2
    port: 10001
    protocol: UDP
    targetPort: unifi-udp2
  externalIPs:
    - "192.168.1.50"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi
  template:
    metadata:
      labels:
        app: unifi
    spec:
      containers:
      - name: unifi
        image: lscr.io/linuxserver/unifi-controller
        imagePullPolicy: Always
        env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        ports:
        - containerPort: 8080
          name: unifi-http
          protocol: TCP
        - containerPort: 8443
          name: unifi-https
          protocol: TCP
        - containerPort: 3478
          name: unifi-udp1
          protocol: UDP
        - containerPort: 10001
          name: unifi-ud2
          protocol: UDP
        readinessProbe:
          tcpSocket:
            port: unifi-https
        volumeMounts:
        - name: unifi-nfs
          mountPath: /config
          readOnly: false
      volumes:
      - name: unifi-nfs
        nfs:
          server: 192.168.1.13
          path: /storage/tank/kubernetes/unifi
