apiVersion: v1
kind: Service
metadata:
  name: transmission-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: transmission
  ports:
  - name: transmission
    port: 9091
    protocol: TCP
    targetPort: transmission
  - name: torrent-tcp
    port: 51412
    protocol: TCP
    targetPort: torrent-tcp
  - name: torrent-udp
    port: 51412
    protocol: UDP
    targetPort: torrent-udp
  externalIPs:
    - "192.168.1.50"
